### ISSUE TITLE
tsd install removes custom .d.ts files in typings directory

### ISSUE THREAD

**Issue by wholroyd** [DefinitelyTyped/tsd#184]
It would be nice to check in my custom *.d.ts files in the `typings` directory, but it seems that if I pull down the repo on another machine, and then run `tsd install` they get deleted. Even if I remove bundling, this still happens.

Or is there another suggested way of storing custom .d.ts files in my repo without them getting whacked?

**Comment by dancarlstedt** [comment]
I would also like to store them in this directory. I'm curious to hear if there is another preferred approach. To me they logically fit in this directory. It would be cool if the tsd.json file had a setting for keeping these files. 

Maybe {"custom-type-file" : "app.d.ts"} then tsd install and reinstall can use this to protect that file.

**Comment by rehmsen** [comment]
+1 - this seems to have changed recently. They used to be left alone, no they are removed.

**Comment by johnpapa** [comment]
not a fan of this either.

but if it stays, i just want a way to keep my custom ones. perhaps a typings/custom folder that is left alone

**Comment by DanWahlin** [comment]
I like the "custom" folder idea.

**Comment by Diullei** [comment]
it was implemented based on this discussion https://github.com/DefinitelyTyped/tsd/issues/151. I implemented an alternative to keep the custom files (discussed here https://github.com/DefinitelyTyped/tsd/issues/179). However I am willing to reverse this change and rethink this implementation.

Maybe a `--clean` flag as @jimlloyd suggested here https://github.com/DefinitelyTyped/tsd/issues/179#issuecomment-115010147 could be a good option.

Would like to help with ideas?

**Comment by alexeagle** [comment]
I am sad that `install` and `reinstall` didn't have stronger meanings to begin with, but given the current situation of people using `reinstall` and expecting unknown typings to remain, it is better not to break them (and introducing the new --keep-unreferenced is still breaking them since they don't know to add that or what it means.)

`reinstall --clean` seems like the right interface to me.

**Comment by johnpapa** [comment]
I agree. `reinstall --clean` seems the best options of non breaking change and still getting the right behavior


or 

`reinstall -c`

**Comment by DanWahlin** [comment]
+1. Using a --clean switch makes a lot more sense. It's never fun to be surprised by a tool that was "reinstalling" something while also deleting at the same time. :-)

**Comment by Diullei** [comment]
Ok! I'll reverse this code and implement with `--clean` switch.

**Comment by wholroyd** [comment]
That would be awesome @Diullei - thanks!

**Comment by DanWahlin** [comment]
Great to hear - thanks @Diullei! Sounds like a great way to go with it.

**Comment by johnpapa** [comment]
@Diullei Thank you!

**Comment by johnpapa** [comment]
When will this be on npm?

**Comment by Diullei** [comment]
Hi! The TravisCI has broken. I'll fix it before merge my PR. I intend to release a new version until this weekend. I'll try to add another fixes.

**Comment by SirDarquan** [comment]
Hi @Diullei Thanks for getting on this issue as I've just run into it also. I wanted to chime in to make sure I understand what is going to happen going forward. In v0.6.1, invoking the reinstall command will update the references in the tsd.json file and will not clean stale references nor remove my custom typings which seems to be what most people on this thread prefer. By introducing the --clean switch, it becomes 'ok' to delete our custom typings because it's an explicit command? If I'm misunderstanding how this is supposed to work, please correct me because under no circumstance would I want my typings deleted unless I or my developers did it.

**Comment by Diullei** [comment]
@SirDarquan, I guess you understood correct. With this change, the `reinstall` command will remove your custom typing only if you use the `--clean` flag. 

```
tsd reinstall --clean
```
If not, the `reinstall` command will reinstall all typings and keep your custom typings, like the 0.6.1 version.

**Comment by Diullei** [comment]
Hey! 

I published a beta version of tsd with the last changes. This changes include the code regression that use the `--clean` flag with `reinstall` command.

```
npm install tsd@0.6.4-beta -g
```

Please, let me know if you have any issue with this version.

**Comment by johnpapa** [comment]
Thanks! i will try it out and get you some feedback tomorrow

**Comment by johnpapa** [comment]
it works!

**Comment by Diullei** [comment]
@johnpapa thanks for the feedback!

**Comment by johnpapa** [comment]
thank you for doing this. looking forward to it being released

**Comment by Diullei** [comment]
Hi! I just published a new version to npm (0.6.4) with the fix. Please, let me know if you have any problems.

**Comment by alexeagle** [comment]
I can verify this works with a config file in the root folder, but doesn't seem to work in Angular where we keep the tsd.json files under a couple different subdirectories. Do `--clean` and `--config` work together?
```
$ ./node_modules/.bin/tsd | head
>> tsd 0.6.4
$ mkdir tools/typings/blah
$ touch tools/typings/blah.d.ts
$ ./node_modules/.bin/tsd reinstall --clean --config tools/tsd.json
$ ls tools/typings/blah/
blah.d.ts
```

Can you repro, or should I try to make a standalone example?
Thanks!

**Comment by Diullei** [comment]
Hi @alexeagle! 

I reproduced your problem. I will work to correct it today and send a fix until tomorrow.

thanks for reporting this issue.

**Comment by srowan** [comment]
Perhaps consider adding --clean flag as an option for `tsd install` ?   i.e. `tsd install --clean`.
